# Generated by Django 4.1.2 on 2023-03-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='Image',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
