# Generated by Django 4.1.2 on 2023-03-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_salesdata_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
