# Generated by Django 4.1.2 on 2023-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_alter_salesdata_quantity_alter_salesdata_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
