# Generated by Django 4.1.2 on 2023-03-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_alter_salesdata_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='orderno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='vtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
